name: dm4bem-env

channels:
  - conda-forge

dependencies:
  - python=3.9.12
  - jupyter=1.0.0
  - jupyterlab>=3.3.2
  - ipywidgets=7.6.5
  - matplotlib=3.5.1
  - numpy=1.21.5
  - scipy=1.7.3
  - pandas=1.4.2
  - voila>=0.2.11
